### ISSUE TITLE
Missing Theme

### ISSUE THREAD

**Issue by jacobmort** [ubien/MuzeiGooglePhotos#15]
java.lang.RuntimeException: Unable to start activity ComponentInfo{porqueno.muzeigooglephotos/porqueno.muzeigooglephotos.activities.PhotosAuthActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
    at android.support.v7.a.s.n(SourceFile:310)
    at android.support.v7.a.s.m(SourceFile:279)
    at android.support.v7.a.s.a(SourceFile:253)
    at android.support.v7.a.ab.setContentView(SourceFile:76)
    at android.support.v7.a.b.a(SourceFile:213)
    at android.support.v7.a.l.onCreate(SourceFile:240)
    at android.app.Dialog.dispatchOnCreate(Dialog.java:394)
    at android.app.Dialog.show(Dialog.java:295)
    at a.a.a.b.a(SourceFile:133)
    at a.a.a.b.a(SourceFile:84)
    at porqueno.muzeigooglephotos.activities.PhotosAuthActivity.d(SourceFile:107)
    at porqueno.muzeigooglephotos.activities.PhotosAuthActivity.c(SourceFile:70)
    at porqueno.muzeigooglephotos.activities.PhotosAuthActivity.onCreate(SourceFile:56)
    at android.app.Activity.performCreate(Activity.java:6251)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
    ... 9 more

**Comment by jacobmort** [comment]
Still happening
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{porqueno.muzeigooglephotos/porqueno.muzeigooglephotos.activities.PhotosAuthActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at android.support.v7.a.j.n(Unknown Source)
	at android.support.v7.a.j.m(Unknown Source)
	at android.support.v7.a.j.a(Unknown Source)
	at android.support.v7.a.k.setContentView(Unknown Source)
	at android.support.v7.a.b.a(Unknown Source)
	at android.support.v7.a.c.onCreate(Unknown Source)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:389)
	at android.app.Dialog.show(Dialog.java:293)
	at b.a.a.b.a(Unknown Source)
	at b.a.a.b.a(Unknown Source)
	at porqueno.muzeigooglephotos.activities.PhotosAuthActivity.d(Unknown Source)
	at porqueno.muzeigooglephotos.activities.PhotosAuthActivity.c(Unknown Source)
	at porqueno.muzeigooglephotos.activities.PhotosAuthActivity.onCreate(Unknown Source)
	at android.app.Activity.performCreate(Activity.java:6664)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
	... 9 more```
