### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by jacobmort** [ubien/MuzeiGooglePhotos#3]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.job.IJobCallback android.app.job.JobParameters.getCallback()' on a null object reference
    at android.app.job.JobService$JobHandler.handleMessage(JobService.java:161)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6077)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by ghost** [comment]
Hi, how did you fixed this issue?

**Comment by llatour** [comment]
Hi, I'm also having this issue. Did you fixed it ?

**Comment by ghost** [comment]
I did not. I found this is not happening on production version. But also I'm on the edge to refactor JobScheduler because it's unstable old android versions.

**Comment by llatour** [comment]
Looking at ubien delivery that closed the issue, I found the issue:
Calling jobFinished with null JobParameters causes this exception. 
Having multiple jobs scheduled/cancelled caused this exception for me: if the job is cancelled, but the task of the jobs finishes anyway, and a new job is scheduled, calling jobFinished with the stopped job parameters causes this crash.
